name: Export requirements.txt for Binder

on:
  push:
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  export-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry

      - name: Add export plugin
        run: poetry self add poetry-plugin-export

      - name: Export requirements.txt
        run: |
          poetry export -f requirements.txt --without-hashes -o requirements.txt
          echo "-e ." >> requirements.txt

      - name: Commit and push requirements.txt if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add requirements.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update requirements.txt from pyproject.toml"
          git push
